### PR TITLE
[IMP] theme_*: adapt `s_text_image`, `s_image_text`

### PR DESCRIPTION
**Pull request by chgo-odoo**
- Requires : https://github.com/odoo/odoo/pull/173311

task-3665301
part of task-3619705

### CODE REVIEW

**Review by stefanorigano — APPROVED** [review]
...LGTM as well 👍

**Comment by robinlej** [comment]
@robodoo r+

**Comment by bso-odoo** [comment]
@robodoo delegate=robinlej

**Comment by robinlej** [comment]
@robodoo r+

**Comment by robinlej** [comment]
@robodoo rebase-ff

**Pull request closed without merging**
