### PR TITLE
[FIX] theme_kea: adding s_text_image to the theme

### PR DESCRIPTION
**Pull request by jrbr-odoo**
**"s_text_image.jpg" missing in the theme "Kea"**

Impacted versions:
 
 - 17.0
 
Steps to reproduce:
 
 1. Create a website with the theme "Kea". Switching the theme to "Kea" also works. 
 2. Open the website editor and add an inner content of type image
 
Current behavior:
 
 - Throws an Odoo client error:
```
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'size')
TypeError: Cannot read properties of undefined (reading 'size')
    at _getImageSizeFromCache (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:18836:31)
    at apply modifications (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:18748:26)
    at async Class._applyOptions (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:38017:25)
    at async Class._applyOptions (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:38529:21)
    at async Class.start (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:37806:9)
    at async Promise.all (index 19)
    at async Promise.all (index 1)
    at async Class.start (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:42099:9)
    at async Promise.all (index 0)
    at async Class.callPostSnippetDrop (https://58028859-17-0-design_theme.runbot202.odoo.com/web/assets/1/debug/website.backend_assets_all_wysiwyg.js:29362:9)
```

Fixed/Expected behavior:
 
 - To be able to inner content in the theme "Kea". 

opw-3689096

### CODE REVIEW

**Review by qsm-odoo — CHANGES_REQUESTED** [review]
Thanks for the fix :+1: However:
- It would be great to have some kind of explanation as to why this error occurs now and not in 16.4, even though the `s_text_image_default_image` record already existed (maybe since forever actually).
- Commit message conventions:
  - Max 72 characters per line (and use those 72 characters of course)
  - opw instead of OPW

Thank you :pray:

**Comment by jrbr-odoo** [comment]
Hello, thanks for reiterating the commit message conventions. I have changed it to the required format. 

This error doesn't occur until 16.4 because, there was no option to add inner content as image.  

Runbot 16.4 website editor options for inner content:
image

Whereas in Odoo 17 onwards, the website editor has an option to add image as inner content. 

Runbot 17.0 website editor options for inner content:
image

When the user drags an drops the inner content image in the website while on theme Kea, the theme looks for a default image of name `s_text_image.jpg` to be present in the theme directory `/static/src/img/snippets`. This image is not present in the current repository, thus it throws the client error. 

Since the option to add image as inner content is not available until 16.4, it was not possible for the user to encounter this error. Please feel free to reach out if you need more information on this.

**Comment by qsm-odoo** [comment]
> This error doesn't occur until 16.4 because, there was no option to add inner content as image.

@jrbr-odoo Of course but then why was that theme.ir.attachment defined at all in 16.4 ? (`<record id="s_text_image_default_image" model="theme.ir.attachment">`) and why does not it crash for the s_text_image where it is supposed to be used by default => that's the information that should be in the commit message IMO :wink: 

Thanks :pray:

**Comment by jrbr-odoo** [comment]
Heyy @qsm-odoo,

Yes, a record exists in the `theme.ir.attachment` model with the name `website.s_text_image_default_image` for the theme "Kea". 

image


The attachment points to the URL "/theme_kea/static/src/img/snippets/s_text_image.jpg'. The URL returns the status code 404 not found. 

image


Whereas, for the theme artists this is the output. 

image

This means, that the theme requires a file with the name `s_text_image.jpg` to be present in the filestore. Since it's missing the status code returns 404 not found and the editor causes the client error. **The 404 not found error exists even in Odoo 16.4**.I hope that answers the query

**Comment by qsm-odoo** [comment]
@jrbr-odoo

> The 404 not found error exists even in Odoo 16.4

Then why is not there a flow broken in 16.4 and/or why is not this PR targeting 17.0 -> that's the info I need in the commit message.
- The attachment was created in version "X" (commit XXX), and used by feature "A"
- It stopped working in version "Y" (commit YYY) (maybe "Y" == "X"), this PR thus targets "Y" or explains why not.

**Review by qsm-odoo — APPROVED** [review]
I reviewed the entire thing (see commit message for details):
- Two images were missing, not only one.
- Given the investigation, this now targets 15.0 instead of 17.0.
- Re-used existing images of the same theme... so they better match the spirit of the theme. Also to not use the >1Mb image that was suggested.
- Created https://www.odoo.com/web#menu_id=4720&cids=1&action=5050&model=project.task&view_type=form&id=3762775 for a "bug" found while testing.

@robodoo r+

**Pull request closed without merging**
