### PR TITLE
[IMP] *: Remove alias in JS files

### PR DESCRIPTION
**Pull request by bastien-ipb**
Rename all imports with alias old system to the new js module system 
Task ID: 3266759

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+ delegate=@bastien-ipb

**Comment by bastien-ipb** [comment]
robodoo r+

**Comment by seb-odoo** [comment]
@robodoo p=1

**Comment by bastien-ipb** [comment]
robodoo r+

**Pull request closed without merging**
