### PR TITLE
[REF] theme_common: remove underscorejs usages

### PR DESCRIPTION
**Pull request by pipu-odoo**
After this commit, usages of underscore js functions has been replaced by native javascript function.

task-3246238

### CODE REVIEW

**Comment by sdegueldre** [comment]
community PR: https://github.com/odoo/odoo/pull/125889

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by qsm-odoo** [comment]
@robodoo r-

Badly adapted?

**Comment by sdegueldre** [comment]
Looks like I read this too fast, there's an extra layer of function.

**Review by sdegueldre — APPROVED** [review]
@robodoo r+

**Comment by sdegueldre** [comment]
@robodoo r+

**Pull request closed without merging**
