### PR TITLE
[IMP] theme_anelusia, *: adapt `s_company_team_shapes` and optimize team snippet images

### PR DESCRIPTION
**Pull request by Brieuc-brd**
### Optimize team snippet images
This PR optimizes and adapts the images related to s_company_team_* snippet to avoid using multiple versions with differents sizes and ratios.

### Adapt `s_company_team_shapes`
This PR adapts customizations for `s_company_team_shapes`.

task-4140941
Part of task-4077427

---

Requires:
- https://github.com/odoo/odoo/pull/178367

### CODE REVIEW

**Review by anso-odoo — COMMENTED** [review]
Not trying to assume genders or anything, but it looks like some genres have been interchanged from the default theme. IMO we can keep it like that as it's only demo data, but do as you wish 👍 

`theme_aviato`:
Screenshot 2024-08-29 at 17 15 07

`theme_kiddo`:
Screenshot 2024-08-29 at 17 20 12

`theme_notes`:
Screenshot 2024-08-29 at 17 21 46

`theme_yes`:
Screenshot 2024-08-29 at 17 24 44

**Comment by sobo-odoo** [comment]
@robodoo delegate=bvr-odoo

**Review by bvr-odoo — APPROVED** [review]

**Comment by bvr-odoo** [comment]
@robodoo r+

**Comment by bvr-odoo** [comment]
@robodoo rebase-ff r+

**Pull request closed without merging**
