### PR TITLE
[FIX] *: clean useless content in manifests

### PR DESCRIPTION
**Pull request by Feyensv**
Make sure the linting test added in community do not fail.

See odoo/odoo#107735

### CODE REVIEW

**Comment by Feyensv** [comment]
@robodoo r+

**Comment by d-fence** [comment]
@robodoo r+
Nice to rplus the PR 666 😈

**Comment by rdeodoo** [comment]
@d-fence Sorry my lord, I stole the show. Looks like I am your :smiling_imp: on this one :boom:

**Comment by d-fence** [comment]
rhoo too late

**Pull request closed without merging**
