### PR TITLE
[IMP] theme_common: remove PublicWidget fix for deprecated old apple devices

### PR DESCRIPTION
**Pull request by pparidans**
Introduced in https://github.com/odoo/design-themes-old/commit/a3dbaf15767785d2c0e5bdab5ce445b82a38f82b,
this Bootstrap's Collapse fix was targetting very old Apple devices.

task-3439226

Community PR: https://github.com/odoo/odoo/pull/134020

### CODE REVIEW

**Comment by pparidans** [comment]
@odoo/rd-website same as it's community counterpart

**Comment by rdeodoo** [comment]
If the reason why it was introduced is not needed anymore (2018 so could be useless now indeed), you have our blessing :+1: 
https://github.com/odoo/design-themes-old/commit/a3dbaf15767785d2c0e5bdab5ce445b82a38f82b
(Would be great to mention that commit in your commit title)

**Comment by pparidans** [comment]
Commit message updated :+1:

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Comment by rdeodoo** [comment]
@robodoo delegate=@adr-odoo

**Review by adr-odoo — APPROVED** [review]
@robodoo r+

**Pull request closed without merging**
